[build-system]
requires = [
  "setuptools>=45.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.flake8]
max-line-length = 120

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
src_paths = ["src"]
line_length = 120
